"""
initialize constants which are going to use
"""
property_file = "config\knapsack.properties"
# log_file = "logs\knapsack.log"
regex_pattern_english_alphabet = "[a-zA-Z]+$"
regex_pattern_digit = "\d+$"
regex_pattern_range = "\d+-\d+$"
regex_pattern_boolean = "(?i)true$|false$"
regex_pattern_decipher_side_choice = "(?i)^(r|a)$"
foreground_colorant_black = ""
foreground_colorant_red = ""
foreground_colorant_green = ""
foreground_colorant_yellow = ""
foreground_colorant_blue = ""
background_colorant_black = ""
background_colorant_red = ""
background_colorant_green = ""
background_colorant_yellow = ""
background_colorant_blue = ""
background_colorant_white = ""
bold_attribute = ""
attribute_default = ""
terminal_delimiter = "\n*******************"
section_vector = "VectorSection"
section_parameters = "ParametersSection"
algorithm_brute_force = "BruteForce"
algorithm_totient = "Totient"
algorithm_back_tracking = "BackTracking"
structure_type_string = "String"
structure_type_boolean = "Boolean"
structure_type_int = "Int"
structure_type_float = "Float"
